# Generated by Django 3.2.3 on 2021-11-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0004_auto_20211101_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles/'),
        ),
    ]
