# Generated by Django 3.2.3 on 2021-10-23 12:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least three characters!')])),
                ('text', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='last edited')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
