# Generated by Django 3.2.3 on 2021-10-23 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(5, 'Please enter at least five characters!')])),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='background_picture',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='article', to='arts.picture'),
        ),
    ]
