# Generated by Django 3.2.3 on 2021-10-27 04:40

import arts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0007_article_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('English', 'ENGLISH'), ('Nederlands', 'DUTCH'), ('Français', 'FRENCH'), ('Deutsch', 'GERMAN'), ('日本', 'JAPANESE')], default=arts.models.Languages['ENGLISH'], max_length=100),
        ),
    ]
