# Generated by Django 3.2.3 on 2021-10-29 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arts', '0009_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='last edited')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('response_to_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arts.article')),
                ('response_to_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responded_by', to='arts.response')),
            ],
        ),
    ]
