# Generated by Django 3.2.3 on 2021-10-29 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arts', '0010_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='responses',
            field=models.ManyToManyField(related_name='responded_to', through='arts.Response', to=settings.AUTH_USER_MODEL),
        ),
    ]
