# Generated by Django 3.2.3 on 2021-10-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0013_article_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
